version: '3.3'
services:

  frontend:
    image: vadimvolkovsky/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
  
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
    container_name: foodgram_postgres_db

  backend:
    image: vadimvolkovsky/foodgram:latest
    restart: always
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    container_name: foodgram_web

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/backend_static/
      - media_value:/var/html/media/
    depends_on:
      - backend
    container_name: foodgram_nginx

volumes:
  static_value:
  media_value:

